import { Trip } from "@/types/content";

export const trips: Trip[] = [
  {
    id: "trip-half-day",
    slug: "half-day-cda",
    title: "Half-Day Coeur d'Alene Action Trip",
    summary: "High-efficiency morning charter built for consistent action and quick wins.",
    durationHours: 5,
    priceFromUsd: 425,
    maxAnglers: 3,
    skillLevel: "all",
    locationIds: ["cda-lake"],
    speciesIds: ["rainbow", "kokanee"],
    includes: ["Premium tackle", "Safety gear", "Technique coaching"],
    imageUrl: "https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=1400&q=80",
    vallyBookingPath: "half-day-cda",
    isFeatured: true,
    isActive: true,
  },
  {
    id: "trip-full-day",
    slug: "full-day-trophy",
    title: "Full-Day Trophy Hunt",
    summary: "Full-water-time charter for anglers targeting size and peak bite windows.",
    durationHours: 8,
    priceFromUsd: 695,
    maxAnglers: 4,
    skillLevel: "intermediate",
    locationIds: ["cda-lake", "spokane-river"],
    speciesIds: ["chinook", "rainbow"],
    includes: ["Premium tackle", "Electronics scouting", "Shore lunch"],
    imageUrl: "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1400&q=80",
    vallyBookingPath: "full-day-trophy",
    isFeatured: true,
    isActive: true,
  },
  {
    id: "trip-family",
    slug: "family-charter",
    title: "Family Private Charter",
    summary: "Beginner-friendly private day with coaching, safety-first pacing, and memories.",
    durationHours: 6,
    priceFromUsd: 575,
    maxAnglers: 5,
    skillLevel: "beginner",
    locationIds: ["cda-lake"],
    speciesIds: ["kokanee", "rainbow"],
    includes: ["All core gear", "Fish handling instruction", "Photo moments"],
    imageUrl: "https://images.unsplash.com/photo-1464039397811-476f652a343b?auto=format&fit=crop&w=1400&q=80",
    vallyBookingPath: "family-charter",
    isFeatured: true,
    isActive: true,
  },
];
