import { Trip } from "@/types/content";

export const trips: Trip[] = [
  {
    id: "bass-half-day",
    slug: "bass-half-day",
    title: "Half-Day Bass & Pike Trip",
    subtitle: "Lake Coeur d'Alene, Idaho",
    description:
      "High-efficiency morning session built for consistent action on trophy smallmouth and largemouth bass, plus massive pike. Operating from a tournament-rigged Lund Pro-V Bass boat, we strategically target the best structure and cover Lake CDA has to offer.",
    durationHours: 4,
    pricingModel: "per-boat",
    priceUsd: 695,
    baseAnglers: 2,
    extraAnglerPriceUsd: 150,
    maxAnglers: 3,
    skillLevel: "all",
    species: ["Smallmouth Bass", "Largemouth Bass", "Northern Pike"],
    location: "Lake Coeur d'Alene, Idaho",
    seasonLabel: "April – November",
    seasonMonths: [4, 5, 6, 7, 8, 9, 10, 11],
    includes: [
      "All fishing gear, tackle & bait",
      "Beverage selection",
      "Life jackets",
      "Fuel",
    ],
    notIncluded: [
      "State fishing license & catch cards (mandatory)",
      "Proper clothing",
      "Fishing guide gratuity",
    ],
    imageUrl: "/photos/bass-half-day.jpg",
    isFeatured: true,
    bookingPath: "bass-half-day",
    catchAndRelease: true,
    isActive: true,
  },
  {
    id: "bass-full-day",
    slug: "bass-full-day",
    title: "Full-Day Bass & Pike Trip",
    subtitle: "Lake Coeur d'Alene, Idaho",
    description:
      "Full-water-time session for anglers targeting size and peak bite windows. Consistently earning a spot in Bassmaster's top ten best bass fishing lakes, Lake CDA hosts world-class technical bass and pike fishing. Our commitment lies in preserving the true trophy-class fish that inhabit Lake CDA.",
    durationHours: 8,
    pricingModel: "per-boat",
    priceUsd: 995,
    baseAnglers: 2,
    extraAnglerPriceUsd: 225,
    maxAnglers: 3,
    skillLevel: "all",
    species: ["Smallmouth Bass", "Largemouth Bass", "Northern Pike"],
    location: "Lake Coeur d'Alene, Idaho",
    seasonLabel: "April – November",
    seasonMonths: [4, 5, 6, 7, 8, 9, 10, 11],
    includes: [
      "All fishing gear, tackle & bait",
      "Beverage selection",
      "Lunch",
      "Life jackets",
      "Fuel",
    ],
    notIncluded: [
      "State fishing license & catch cards (mandatory)",
      "Proper clothing",
      "Fishing guide gratuity",
    ],
    imageUrl: "/photos/bass-full-day.jpg",
    isFeatured: true,
    bookingPath: "bass-full-day",
    catchAndRelease: true,
    isActive: true,
  },
  {
    id: "steelhead",
    slug: "steelhead",
    title: "Steelhead Fishing Trip",
    subtitle: "Clearwater & Snake Rivers, Idaho",
    description:
      "The Clearwater River is renowned for its legendary B-Run Steelhead, which typically weigh between 12 to 15 pounds — with some lucky anglers landing fish exceeding 20 pounds and measuring over 40 inches. We use various techniques including back trolling with plugs and divers, as well as side drifting with beads or eggs.",
    durationHours: 8,
    pricingModel: "per-seat",
    priceUsd: 285,
    minAnglers: 3,
    maxAnglers: 18,
    skillLevel: "all",
    species: ["Steelhead"],
    location: "Clearwater & Snake Rivers, Idaho",
    seasonLabel: "October – March",
    seasonMonths: [10, 11, 12, 1, 2, 3],
    includes: [
      "All fishing gear, tackle & bait",
      "Beverage selection",
      "Lunch",
      "Life jackets",
      "Fuel",
    ],
    notIncluded: [
      "State fishing license & catch cards (mandatory)",
      "Proper clothing",
      "Fishing guide gratuity",
    ],
    imageUrl: "/photos/steelhead-trip.jpg",
    isFeatured: true,
    bookingPath: "steelhead",
    catchAndRelease: false,
    isActive: true,
  },
  {
    id: "salmon",
    slug: "salmon",
    title: "Salmon Fishing Trip",
    subtitle: "Columbia River, WA / Clearwater & Snake Rivers, ID",
    description:
      "Chase Chinook and Sockeye salmon on some of the Pacific Northwest's most productive waters. Whether you're on the mighty Columbia River in Washington or the Clearwater and Snake rivers in Idaho, these full-day trips put you in the heart of the salmon run with expert guidance and proven techniques.",
    durationHours: 8,
    pricingModel: "per-seat",
    priceUsd: 285,
    minAnglers: 3,
    maxAnglers: 18,
    skillLevel: "all",
    species: ["Chinook Salmon", "Sockeye Salmon"],
    location: "Columbia River, WA / Clearwater & Snake Rivers, ID",
    seasonLabel: "May – October",
    seasonMonths: [5, 6, 7, 8, 9, 10],
    includes: [
      "All fishing gear, tackle & bait",
      "Beverage selection",
      "Lunch (Idaho trips only)",
      "Life jackets",
      "Fuel",
    ],
    notIncluded: [
      "State fishing license & catch cards (mandatory)",
      "Proper clothing",
      "Fishing guide gratuity",
    ],
    imageUrl: "/photos/salmon-trip.jpg",
    isFeatured: true,
    bookingPath: "salmon",
    catchAndRelease: false,
    isActive: true,
  },
];
